# moon47.py - MOON47, the Moon phase page, standalone (generated by tools/build_moon47.py from
# python/moon47.py: the same formulas as MOON47 on the C47 and Free42). Almanac 47.
# Copyright 2026 Victor Valdes. GPL-3.0-or-later. Supports, does not replace, the Nautical Almanac.
import math

# D, M, M', F, longitude (1e-6 deg), distance (1e-3 km)
TERMS = (
    (0, 0, 1, 0, 6288774, -20905355),
    (2, 0, -1, 0, 1274027, -3699111),
    (2, 0, 0, 0, 658314, -2955968),
    (0, 0, 2, 0, 213618, -569925),
    (0, 1, 0, 0, -185116, 48888),
    (0, 0, 0, 2, -114332, 0),
    (2, 0, -2, 0, 58793, 246158),
    (2, -1, -1, 0, 57066, -152138),
    (2, 0, 1, 0, 53322, -170733),
    (2, -1, 0, 0, 45758, -204586),
    (0, 1, -1, 0, -40923, -129620),
    (1, 0, 0, 0, -34720, 108743),
    (0, 1, 1, 0, -30383, 104755),
    (2, 0, 0, -2, 15327, 0),
    (0, 0, 1, 2, -12528, 0),
    (0, 0, 1, -2, 10980, 79661),
    (4, 0, -1, 0, 10675, 0),
    (0, 0, 3, 0, 10034, 0),
    (4, 0, -2, 0, 8548, 0),
    (2, 1, -1, 0, -7888, 0),
)
LUN = 29.530589          # synodic month, days
RATE = 12.190749         # mean elongation, deg a day
DT = 69.0 / 86400.0      # TT - UT (2000-2050: 64-75 s), days
PHASES = ((0.0, 'NEW MOON'), (90.0, 'FIRST QUARTER'), (180.0, 'FULL MOON'), (270.0, 'LAST QUARTER'))
NAMES = ('NEW MOON', 'WAXING CRESCENT', 'FIRST QUARTER', 'WAXING GIBBOUS', 'FULL MOON',
         'WANING GIBBOUS', 'LAST QUARTER', 'WANING CRESCENT')


def sind(x):
    return math.sin(math.radians(x))


def cosd(x):
    return math.cos(math.radians(x))


def julian(y, m, d, ut):
    """JD of the date (Gregorian) at ut hours."""
    if m <= 2:
        y, m = y - 1, m + 12
    a = y // 100
    return int(365.25 * (y + 4716)) + int(30.6001 * (m + 1)) + d + 2 - a + a // 4 - 1524.5 + ut / 24.0


def from_julian(j):
    """(day, month, year, ut hours) of JD j."""
    z = int(j + 0.5); f = j + 0.5 - z
    a = int((z - 1867216.25) / 36524.25)
    a = z + 1 + a - a // 4
    b = a + 1524; c = int((b - 122.1) / 365.25); d = int(365.25 * c); e = int((b - d) / 30.6001)
    day = b - d - int(30.6001 * e)
    mon = e - 1 if e < 14 else e - 13
    return day, mon, (c - 4716 if mon > 2 else c - 4715), f * 24.0


def moon(j):
    """(elongation deg 0-360, distance km, latitude deg, M deg) at JD j (UT)."""
    T = (j + DT - 2451545.0) / 36525.0
    D = 297.8501921 + 445267.1114 * T
    M = 357.5291092 + 35999.05029 * T
    Mp = 134.9633964 + 477198.8675 * T
    F = 93.272095 + 483202.0175 * T
    E = 1.0 - 0.002516 * T
    lon = dist = 0.0
    for d, m, mp, f, cl, cr in TERMS:
        a = d * D + m * M + mp * Mp + f * F
        e = E if m else 1.0
        lon += cl * e * sind(a)
        dist += cr * e * cosd(a)
    c = (1.914602 - 0.004817 * T) * sind(M) + 0.019993 * sind(2 * M) + 0.000289 * sind(3 * M)
    return (D + lon / 1e6 - c + 0.00569) % 360.0, 385000.56 + dist / 1000.0, 5.128189 * sind(F), M


def phase_time(j, target):
    """JD of the first time at or after about j when the elongation is target (deg): the secant method,
    from j and the mean rate's guess, three steps (within 0.01 minute of the converged time)."""
    d = (target - moon(j)[0]) % 360.0
    t0, f0 = j, -d
    t1 = j + d / RATE
    for _ in range(3):
        f1 = (moon(t1)[0] - target + 180.0) % 360.0 - 180.0
        if f1 == f0:
            break
        t0, t1, f0 = t1, t1 - f1 * (t1 - t0) / (f1 - f0), f1
    return t1


def tz_text(tz):
    """The offset of the header: 0, +4, -5, +5:30 (hours, minutes)."""
    if tz == 0:
        return '0'
    a = abs(tz); h = int(a); m = int(a * 60 - h * 60 + 0.5)
    if m == 60:
        h, m = h + 1, 0
    return ('+' if tz > 0 else '-') + str(h) + (':%02d' % m if m else '')


def header_text(j, tz):
    """The top line: the clock's date and time (UT when TZ = 0, else LT = UT + TZ) and TZ."""
    d, m, y, h = from_julian(j + tz / 24.0 + 0.5 / 1440)
    return '%02d-%02d-%04d %02d:%02d %s TZ=%s' % (d, m, y, int(h), int(h * 60) % 60, 'LT' if tz else 'UT', tz_text(tz))


def disc_runs(r, age, south, dx):
    """The disc, one column at a time (what AGRAPH draws): for column dx (-r..r) the runs (a, b) of rows,
    a <= |y| <= b above and below the centre. The lit part is filled, the dark part is the outline;
    waxing lit on the right (northern view), mirrored for the south. Same pixels as the test
    'lit or outline' of every pixel (x right of the terminator x = w cos(age), w the half width)."""
    ct = cosd(age / LUN * 360.0) or 1e-30
    v = (-dx if south else dx) * (1 if age <= LUN / 2 else -1)
    ymax = math.floor(math.sqrt((r + 0.3) ** 2 - dx * dx))
    qi = (r - 1.2) ** 2 - dx * dx
    out = [(0 if qi < 0 else math.floor(math.sqrt(qi)) + 1, ymax)]          # the outline
    q = r * r - (v / ct) ** 2
    if ct >= 0:
        if v > 0:
            out.append((0 if q < 0 else math.floor(math.sqrt(q)) + 1, ymax))
    elif v >= 0:
        out.append((0, ymax))
    elif q > 0:
        out.append((0, min(ymax, math.floor(math.sqrt(q)))))
    return [(a, b) for a, b in out if a <= b]


def page(j, south=False):
    """Everything MOON47 shows, at JD j (UT)."""
    e, dist, beta, M = moon(j)
    psi = math.degrees(math.acos(cosd(beta) * cosd(e)))                       # Sun-Moon angle
    r = 149597870.7 * (1.000140 - 0.016708 * cosd(M) - 0.000141 * cosd(2 * M))  # Sun distance, km
    i = math.degrees(math.atan2(r * sind(psi), dist - r * cosd(psi)))           # phase angle
    new = phase_time(j - e / RATE - 1.0, 0.0)                                   # the last new Moon
    if new > j:
        new = phase_time(new - LUN - 1.0, 0.0)
    age = j - new
    nxt = []
    for a, name in PHASES:
        t = phase_time(j, a)
        if t < j:                                                               # just passed: the next one
            t = phase_time(t + LUN - 2.0, a)
        nxt.append((t, name))
    nxt.sort()
    return {'jd': j, 'lit': (1.0 + cosd(i)) * 50.0, 'age': age,
            'hp': math.degrees(math.asin(6378.14 / dist)) * 60.0, 'sd': 358473400.0 / dist / 60.0,
            'index': int(age / LUN * 8 + 0.5) % 8, 'next': nxt, 'south': south, 'elongation': e}


# ---------------------------------------------------------------------- the page on the NumWorks (320 x 222)
from kandinsky import fill_rect, color
from ion import keydown, KEY_OK, KEY_EXE, KEY_BACK
from time import sleep

BK = color(0, 0, 0)
WH = color(255, 255, 255)
GR = color(140, 140, 140)
# 5x7 font of the C47 programs (nwlib.py) with ( and ); 7 column bytes per character, bit 6 = top row
C = " %'-./0123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZ()"
F = (b'\x00\x00\x00\x00\x00\x00\x00bd\x08\x13#\x00\x00\x00\x00`\x00\x00\x00\x00\x08\x08\x08\x08\x08\x00\x00\x00\x03\x03\x00\x00\x00\x00\x02\x04\x08\x10 \x00\x00>EIQ>\x00\x00\x00!\x7f\x01\x00\x00\x00!CEI1\x00\x00BAQiF\x00\x00\x0c\x14$\x7f\x04\x00\x00rQQQN\x00\x00\x1e)II\x06\x00\x00@GHP`\x00\x006III6\x00\x000IIJ<\x00\x00\x0066\x00\x00\x00\x00?HHH?\x00\x00\x7fIII6\x00\x00>AAA"\x00\x00\x7fAA"\x1c\x00\x00\x7fIIIA\x00\x00\x7fHHH@\x00\x00>AII/\x00\x00\x7f\x08\x08\x08\x7f\x00\x00\x00A\x7fA\x00\x00\x00\x02\x01A~@\x00\x00\x7f\x08\x14"A\x00\x00\x7f\x01\x01\x01\x01\x00\x00\x7f \x18 \x7f\x00\x00\x7f\x10\x08\x04\x7f\x00\x00>AAA>\x00\x00\x7fHHH0\x00\x00>AEB=\x00\x00\x7fHLJ1\x00\x001IIIF\x00\x00@@\x7f@@\x00\x00~\x01\x01\x01~\x00\x00|\x02\x01\x02|\x00\x00~\x01\x0e\x01~\x00\x00c\x14\x08\x14c\x00\x00p\x08\x07\x08p\x00\x00CEIQa\x00\x00\x10\x1b\x1e|\x1e\x1b\x10\x1c"AIA"\x1c'[:7 * 43]
     + b'\x00\x1c"A\x00\x00\x00' + b'\x00A"\x1c\x00\x00\x00')
# the eight Moon phases, 7x7 (0 new ... 4 full ... 7 waning crescent; waxing lit on the right)
MP = b'\x1c"AAA"\x1c\x1c"AAA>\x1c\x1c"AA\x7f>\x1c\x1c"\x7f\x7f\x7f>\x1c\x1c>\x7f\x7f\x7f>\x1c\x1c>\x7f\x7f\x7f"\x1c\x1c>\x7f\x7fA"\x1c\x1c>AAA"\x1c'


def cols(b, i, w, x, y, c=BK):
    for k in range(w):
        v = b[i + k]
        r = 0
        while r < 7:
            if v >> (6 - r) & 1:
                t = r
                while r < 7 and v >> (6 - r) & 1:
                    r += 1
                fill_rect(x + k, y + t, 1, r - t, c)
            r += 1


def text(s, x, y, c=BK):
    for ch in s:
        i = C.find(ch)
        if i > 0:
            cols(F, 7 * i, 5, x, y, c)
        x += 6
    return x


def draw(j, south):
    p = page(j, south)
    fill_rect(0, 0, 320, 222, WH)
    d, m, y, h = from_julian(j + 0.5 / 1440)
    text('%02d-%02d-%04d %02d:%02d UT' % (d, m, y, int(h), int(h * 60) % 60), 0, 2)
    fill_rect(0, 12, 320, 1, BK)
    cx, cy, r = 66, 118, 56
    for dx in range(-r, r + 1):
        for a, b in disc_runs(r, p['age'], south, dx):
            if a == 0:
                fill_rect(cx + dx, cy - b, 1, 2 * b + 1, BK)
            else:
                fill_rect(cx + dx, cy - b, 1, b - a + 1, BK)
                fill_rect(cx + dx, cy + a, 1, b - a + 1, BK)
    X = 136
    text(NAMES[p['index']], X, 20)
    text('LIT %d%%   AGE %.1f DAYS' % (int(p['lit'] + 0.5), p['age']), X, 34)
    text("HP %.1f'  SD %.1f'" % (p['hp'], p['sd']), X, 46)
    fill_rect(X, 60, 180, 1, BK)
    text('NEXT PHASES (UT)', X, 66)
    yy = 80
    for t, name in p['next']:
        d, m, y, h = from_julian(t + 0.5 / 1440)
        text(name, X, yy)
        text('%02d-%02d %02d:%02d' % (d, m, int(h), int(h * 60) % 60), X + 90, yy)
        yy += 12
    for k in range(8):
        x = X + 22 * k
        if k == p['index']:
            fill_rect(x - 2, 144, 11, 11, BK)
        cols(MP, 7 * k, 7, x, 146, WH if k == p['index'] else BK)
    text('AS SEEN FROM THE SOUTH' if south else 'AS SEEN FROM THE NORTH', X, 166)
    text('OK NORTH/SOUTH   BACK EXIT', X, 200, GR)


def ask():
    # the NumWorks has no clock: the date and the time UT
    y = int(input('Year? '))
    m = int(input('Month? '))
    d = int(input('Day? '))
    u = input('UT hh:mm? ').replace(':', ' ').replace('.', ' ').split()
    return julian(y, m, d, int(u[0]) + (int(u[1]) if len(u) > 1 else 0) / 60.0)


def key():
    while 1:
        for k in (KEY_OK, KEY_EXE, KEY_BACK):
            if keydown(k):
                while keydown(k):
                    sleep(0.02)
                return k
        sleep(0.03)


def run():
    j = ask()
    south = False
    while 1:
        draw(j, south)
        if key() == KEY_BACK:
            break
        south = not south


run()
